name: Releases

on:
  push:
    tags:
      - v*
  workflow_run:
    workflows: ["check package on main"]
    types:
      - completed

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
      body: ${{ steps.get-tag.outputs.body }}
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        run: |
          TAG=$(git tag --contains $(git rev-parse HEAD))
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          TAG_BODY=$(git tag --contains $(git rev-parse HEAD) -n100 | awk '(NR>2)')
          echo "body=$TAG_BODY" >> $GITHUB_OUTPUT
        id: get-tag
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: prepare
    steps:
      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{needs.prepare.outputs.tag}}
          tag: ${{needs.prepare.outputs.tag}}
          body: ${{needs.prepare.outputs.tag}}
